spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:mockapp}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:mockapp}
    password: ${DB_PASSWORD:mockapp}
    hikari:
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
