spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: false
          use_query_cache: false
  sql:
    init:
      mode: never

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: ERROR
